defmodule Day08Test do
  use ExUnit.Case
  doctest Day08

  describe "Testing the day" do
    setup do
      sample = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
	  [
       content: Day08.parseInput(sample)
    ]
    end

    test "part1 sample", fixture do
      assert Day08.part1(fixture.content) == 14
    end

    test "part2 sample", fixture do
      assert Day08.part2(fixture.content) == 34
    end
  end
end
